name: Build and Zip Chrome Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
 
      - name: Install dependencies
        run: yarn
 
      - name: Build Chrome
        run: yarn build:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vite-web-extension-chrome
          path: dist_chrome

      - name: Compress the directory
        run: |
          cd dist_chrome && zip -r "../${{ github.event.repository.name }}.zip" .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.event.repository.name }}.zip
